/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedRoadmapsNewRouteImport } from './routes/_authed/roadmaps/new'
import { Route as AuthedRoadmapsIdRouteImport } from './routes/_authed/roadmaps/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRoadmapsNewRoute = AuthedRoadmapsNewRouteImport.update({
  id: '/roadmaps/new',
  path: '/roadmaps/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRoadmapsIdRoute = AuthedRoadmapsIdRouteImport.update({
  id: '/roadmaps/$id',
  path: '/roadmaps/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/roadmaps/$id': typeof AuthedRoadmapsIdRoute
  '/roadmaps/new': typeof AuthedRoadmapsNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/roadmaps/$id': typeof AuthedRoadmapsIdRoute
  '/roadmaps/new': typeof AuthedRoadmapsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/roadmaps/$id': typeof AuthedRoadmapsIdRoute
  '/_authed/roadmaps/new': typeof AuthedRoadmapsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/roadmaps/$id' | '/roadmaps/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/roadmaps/$id' | '/roadmaps/new'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/'
    | '/_authed/roadmaps/$id'
    | '/_authed/roadmaps/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roadmaps/new': {
      id: '/_authed/roadmaps/new'
      path: '/roadmaps/new'
      fullPath: '/roadmaps/new'
      preLoaderRoute: typeof AuthedRoadmapsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roadmaps/$id': {
      id: '/_authed/roadmaps/$id'
      path: '/roadmaps/$id'
      fullPath: '/roadmaps/$id'
      preLoaderRoute: typeof AuthedRoadmapsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedRoadmapsIdRoute: typeof AuthedRoadmapsIdRoute
  AuthedRoadmapsNewRoute: typeof AuthedRoadmapsNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedRoadmapsIdRoute: AuthedRoadmapsIdRoute,
  AuthedRoadmapsNewRoute: AuthedRoadmapsNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
